name: zsturgess BanLogger
main: me.zsturgess.banlogger.BanLogger
version: 0.1

commands:
  log:
    description: The BanLogger command. For help type /log by itself
    usage: /log ?
    permssion: banLogger.use
    permission-message: You don't have the required permissions to use BanLogger.

permissions:
  banLogger.use:
    description: Allows access to /log
    default: op